// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: disql.proto

package disql

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Participant_Prepare_FullMethodName       = "/disql.Participant/Prepare"
	Participant_Commit_FullMethodName        = "/disql.Participant/Commit"
	Participant_RollBack_FullMethodName      = "/disql.Participant/RollBack"
	Participant_NewConnection_FullMethodName = "/disql.Participant/NewConnection"
)

// ParticipantClient is the client API for Participant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParticipantClient interface {
	Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	RollBack(ctx context.Context, in *RollBackRequest, opts ...grpc.CallOption) (*RollBackResponse, error)
	NewConnection(ctx context.Context, in *NewConnectionRequest, opts ...grpc.CallOption) (*NewConnectionResponse, error)
}

type participantClient struct {
	cc grpc.ClientConnInterface
}

func NewParticipantClient(cc grpc.ClientConnInterface) ParticipantClient {
	return &participantClient{cc}
}

func (c *participantClient) Prepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, Participant_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *participantClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, Participant_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *participantClient) RollBack(ctx context.Context, in *RollBackRequest, opts ...grpc.CallOption) (*RollBackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollBackResponse)
	err := c.cc.Invoke(ctx, Participant_RollBack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *participantClient) NewConnection(ctx context.Context, in *NewConnectionRequest, opts ...grpc.CallOption) (*NewConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewConnectionResponse)
	err := c.cc.Invoke(ctx, Participant_NewConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParticipantServer is the server API for Participant service.
// All implementations must embed UnimplementedParticipantServer
// for forward compatibility.
type ParticipantServer interface {
	Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	RollBack(context.Context, *RollBackRequest) (*RollBackResponse, error)
	NewConnection(context.Context, *NewConnectionRequest) (*NewConnectionResponse, error)
	mustEmbedUnimplementedParticipantServer()
}

// UnimplementedParticipantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParticipantServer struct{}

func (UnimplementedParticipantServer) Prepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedParticipantServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedParticipantServer) RollBack(context.Context, *RollBackRequest) (*RollBackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollBack not implemented")
}
func (UnimplementedParticipantServer) NewConnection(context.Context, *NewConnectionRequest) (*NewConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewConnection not implemented")
}
func (UnimplementedParticipantServer) mustEmbedUnimplementedParticipantServer() {}
func (UnimplementedParticipantServer) testEmbeddedByValue()                     {}

// UnsafeParticipantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParticipantServer will
// result in compilation errors.
type UnsafeParticipantServer interface {
	mustEmbedUnimplementedParticipantServer()
}

func RegisterParticipantServer(s grpc.ServiceRegistrar, srv ParticipantServer) {
	// If the following call pancis, it indicates UnimplementedParticipantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Participant_ServiceDesc, srv)
}

func _Participant_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Participant_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantServer).Prepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Participant_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Participant_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Participant_RollBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollBackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantServer).RollBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Participant_RollBack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantServer).RollBack(ctx, req.(*RollBackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Participant_NewConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantServer).NewConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Participant_NewConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantServer).NewConnection(ctx, req.(*NewConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Participant_ServiceDesc is the grpc.ServiceDesc for Participant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Participant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "disql.Participant",
	HandlerType: (*ParticipantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Participant_Prepare_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Participant_Commit_Handler,
		},
		{
			MethodName: "RollBack",
			Handler:    _Participant_RollBack_Handler,
		},
		{
			MethodName: "NewConnection",
			Handler:    _Participant_NewConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disql.proto",
}
